document.writeln("<script src=\'./lib/jquery-3.3.1.js\'></script>");
document.writeln("    <script src=\'./js/header.js\'></script>");
document.writeln("    <script src=\'./js/nav.js\'></script>");
document.writeln("    <script src=\'./js/Carousel.js\'></script>");
document.writeln("    <script src=\'./js/tradeLink.js\'></script>");
document.writeln("    <script src=\'./js/footer.js\'></script>");
document.writeln("    <script>");
document.writeln("        $(function () {");
document.writeln("            header({");
document.writeln("                containerId: \'#header\',");
document.writeln("                logoSrc: \'./img/logo2.jpg\',");
document.writeln("                homeUrl: \'#\',");
document.writeln("                title1: \'20年 专 注 于 室 内 环 境，零 增 项 的 空 调 系 统\',");
document.writeln("                title2: \'向顾客提供省心，放心，舒心的建筑环境体系化配套服务\',");
document.writeln("                tel1: \'13810704395\',");
document.writeln("                tel2: \'010-63256708\'");
document.writeln("            })");
document.writeln("            nav({");
document.writeln("                containerId: \'#nav\',");
document.writeln("                navArr: [");
document.writeln("                    {");
document.writeln("                        text: \'首 页\',");
document.writeln("                        url: \'index.html\'");
document.writeln("                    },");
document.writeln("                    {");
document.writeln("                        text: \'商用中央空调\',");
document.writeln("                        url: \'commercialCentral.html\'");
document.writeln("                    },");
document.writeln("                    {");
document.writeln("                        text: \'家用中央空调\',");
document.writeln("                        url: \'householdCentral.html\'");
document.writeln("                    },");
document.writeln("                    {");
document.writeln("                        text: \'民用场所案例\',");
document.writeln("                        url: \'civil.html\'");
document.writeln("                    },");
document.writeln("                    {");
document.writeln("                        text: \'商业场所案例\',");
document.writeln("                        url: \'business.html\'");
document.writeln("                    }, {");
document.writeln("                        text: \'工业场所案例\',");
document.writeln("                        url: \'industrial.html\'");
document.writeln("                    },");
document.writeln("                    {");
document.writeln("                        text: \'质量保障措施\',");
document.writeln("                        url: \'qualityAssurance.html\'");
document.writeln("                    },");
document.writeln("                ]");
document.writeln("            })");
document.writeln("");
document.writeln("            $(\'#carousel\').Carousel({");
document.writeln("                imgArr: [");
document.writeln("                    \'https://ss1.baidu.com/9vo3dSag_xI4khGko9WTAnF6hhy/image/h%3D300/sign=77d1cd475d43fbf2da2ca023807fca1e/9825bc315c6034a8ef5250cec5134954082376c9.jpg\',");
document.writeln("                    \'https://ss3.baidu.com/-fo3dSag_xI4khGko9WTAnF6hhy/image/h%3D300/sign=b5e4c905865494ee982209191df4e0e1/c2cec3fdfc03924590b2a9b58d94a4c27d1e2500.jpg\',");
document.writeln("                    \'https://ss2.baidu.com/-vo3dSag_xI4khGko9WTAnF6hhy/image/h%3D300/sign=0c78105b888ba61ec0eece2f713597cc/0e2442a7d933c8956c0e8eeadb1373f08202002a.jpg\',");
document.writeln("                    \'https://ss1.baidu.com/9vo3dSag_xI4khGko9WTAnF6hhy/image/h%3D300/sign=92afee66fd36afc3110c39658318eb85/908fa0ec08fa513db777cf78376d55fbb3fbd9b3.jpg\',");
document.writeln("                    \'https://ss0.baidu.com/94o3dSag_xI4khGko9WTAnF6hhy/image/h%3D300/sign=a62e824376d98d1069d40a31113eb807/838ba61ea8d3fd1fc9c7b6853a4e251f94ca5f46.jpg\'");
document.writeln("                ],");
document.writeln("                switchSpeed: 5000,");
document.writeln("                switchTime: 800");
document.writeln("            })");
document.writeln("");
document.writeln("");
document.writeln("            tradeLink({");
document.writeln("                containerId: \'#trade-link\',");
document.writeln("                arr: [");
document.writeln("                    {");
document.writeln("                        text: \'行业链接1\',");
document.writeln("                        url: \'#\'");
document.writeln("                    },");
document.writeln("                    {");
document.writeln("                        text: \'行业链接2\',");
document.writeln("                        url: \'#\'");
document.writeln("                    },");
document.writeln("                    {");
document.writeln("                        text: \'行业链接3\',");
document.writeln("                        url: \'#\'");
document.writeln("                    },");
document.writeln("                    {");
document.writeln("                        text: \'行业链接4\',");
document.writeln("                        url: \'#\'");
document.writeln("                    }, {");
document.writeln("                        text: \'行业链接5\',");
document.writeln("                        url: \'#\'");
document.writeln("                    },");
document.writeln("                    {");
document.writeln("                        text: \'行业链接6\',");
document.writeln("                        url: \'#\'");
document.writeln("                    },");
document.writeln("                    {");
document.writeln("                        text: \'联系我们\',");
document.writeln("                        url: \'#\'");
document.writeln("                    },");
document.writeln("                ]");
document.writeln("            })");
document.writeln("            footer({");
document.writeln("                containerId: \'#footer\',");
document.writeln("            })");
document.writeln("        })");
document.writeln("    </script>");